import {
  AtSign,
  BadgeCheck,
  BookOpen,
  Bot,
  Box,
  Camera,
  Cloud,
  Code2,
  Cpu,
  CreditCard,
  Database,
  Eye,
  FileText,
  Film,
  Gamepad2,
  Gift,
  Globe,
  Heart,
  KeyRound,
  Layers,
  Link2,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Music2,
  PenTool,
  Play,
  Rocket,
  Server,
  ShieldCheck,
  Sparkles,
  Terminal,
  ThumbsUp,
  Tv,
  User,
  Users,
  Video,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Registri glyph ikon produk. Glyph disimpan sebagai string di mock data
 * agar data produk serializable lintas server → client (RSC).
 */
export const iconRegistry: Record<string, LucideIcon> = {
  "at-sign": AtSign,
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  camera: Camera,
  cloud: Cloud,
  "code-2": Code2,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  eye: Eye,
  "file-text": FileText,
  film: Film,
  gamepad: Gamepad2,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  "key-round": KeyRound,
  layers: Layers,
  link: Link2,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  monitor: Monitor,
  "music-2": Music2,
  "pen-tool": PenTool,
  play: Play,
  rocket: Rocket,
  server: Server,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  terminal: Terminal,
  "thumb-up": ThumbsUp,
  tv: Tv,
  user: User,
  users: Users,
  video: Video,
  wifi: Wifi,
  workflow: Workflow,
  zap: Zap,
};

export function resolveIcon(key: string): LucideIcon {
  return iconRegistry[key] ?? Box;
}

export const iconFallback = Box;