"""
CROWN AI LUXURY - Exclusive Top-6 AI Subscriptions Catalog
Curated VIP Selection: ChatGPT, Claude, Perplexity, Grok, Cursor, Leonardo
Official Verified Subscription Plans & Billing Cadences (Verified September 2026)
Source of Truth Architecture: Clear Separation Between Official Provider Baseline & Store Selling Price
Discount: 48.8% Applied to Store Selling Prices
Sorted by Price: Ascending (Termurah ke Termahal)
"""

PRODUCTS = {
    "chatgpt": {
        "id": "chatgpt",
        "name": "ChatGPT",
        "icon": "🌐",
        "category": "Conversational & Reasoning",
        "badge": "OFFICIAL OPENAI CHATGPT",
        "official_provider": "OpenAI",
        "description_en": "Official OpenAI ChatGPT subscriptions: Plus, Business Standard (Monthly & Annual), Pro ($100 Tier / Pro 5X), Business Premium, and Pro ($200 Tier - Active renewals) featuring OpenAI's advanced reasoning models, Deep Research, and Canvas.",
        "description_id": "Layanan resmi OpenAI: ChatGPT Plus (Bulanan Resmi), Business Standard (Bulanan & Tahunan), Pro ($100 Tier / Pro 5X), Business Premium, dan Pro ($200 Tier - Akun siap pakai/perpanjangan aktif). Ditenagai model penalaran resmi OpenAI, agen otonom Deep Research, dan Canvas. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "plus_1m",
                "short_name_id": "Plus (1 Bulan)",
                "short_name_en": "Plus (1 Month)",
                "name_en": "ChatGPT Plus — 1 Month Official (30 Days)",
                "name_id": "ChatGPT Plus — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "ChatGPT Plus",
                "official_price_monthly": "$20/month",
                "official_price_yearly": "N/A (No Official Annual Billing)",
                "official_billing": "Monthly Only",
                "official_models": "OpenAI Advanced Reasoning & Coding Models",
                "official_features": "Priority access, Deep Research, Canvas workspace, Advanced Voice, file uploads",
                "source_status": "VERIFIED",
                "price_usd": 5.12,
                "price_idr": 82000,
                "store_price_usd": 5.12,
                "store_price_idr": 82000,
                "stock": 85,
                "sold": 2150,
                "type": "Langganan Resmi 100% (Bulanan Resmi $20/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi bulanan OpenAI ($20/bulan tier): Akses penuh ke model penalaran OpenAI, agen riset otonom Deep Research, generator gambar DALL-E, ruang kerja Canvas, dan Advanced Voice Mode.",
                "how_to_use": "1. Akun siap pakai (Email + Password) dikirimkan otomatis oleh bot.\n2. Login melalui https://chatgpt.com atau aplikasi resmi di iOS/Android/macOS/Windows.\n3. Langganan aktif selama 30 hari penuh dengan proteksi garansi total.",
                "notes": "Langganan legal dan resmi 100%. OpenAI hanya menyediakan billing bulanan untuk Plus. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "business_std_1m",
                "short_name_id": "Business Std (1 Bulan)",
                "short_name_en": "Business Std (1 Month)",
                "name_en": "ChatGPT Business Standard — 1 Month (Billed Monthly)",
                "name_id": "ChatGPT Business Standard — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "ChatGPT Business Standard",
                "official_price_monthly": "$25/user/month (Monthly Billing)",
                "official_price_yearly": "$240/user/year ($20/user/mo billed annually)",
                "official_billing": "Monthly & Annual (Min 2 Seats)",
                "official_models": "ChatGPT Business Standard & Codex Models",
                "official_features": "Standard usage limits, Zero Data Retention by default, Admin Console, Custom GPTs sharing",
                "source_status": "VERIFIED",
                "price_usd": 6.40,
                "price_idr": 102000,
                "store_price_usd": 6.40,
                "store_price_idr": 102000,
                "stock": 40,
                "sold": 670,
                "type": "Langganan Resmi 100% (Business Standard $25/User/Bulan • Zero Data Retention)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Batas pesan 2x lebih besar dari Plus, privasi enterprise (Zero Data Retention — percakapan tidak dipakai untuk melatih AI), Custom GPTs sharing dalam tim, dan konsol admin.",
                "how_to_use": "1. Cantumkan alamat email akun ChatGPT Anda saat pemesanan.\n2. Undangan resmi OpenAI Business Standard akan dikirimkan ke email tersebut.\n3. Klik 'Accept Invite', login, lalu pilih workspace Business.",
                "notes": "Langganan legal dan resmi 100%. Menggantikan format legacy ChatGPT Team. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "pro_100_1m",
                "short_name_id": "Pro 5X $100 (1 Bulan)",
                "short_name_en": "Pro 5X $100 (1 Month)",
                "name_en": "ChatGPT Pro ($100 Plan / Pro 5X) — 1 Month Official",
                "name_id": "ChatGPT Pro ($100 Plan / Pro 5X) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "ChatGPT Pro $100 Tier",
                "official_price_monthly": "$100/month",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "OpenAI Advanced High-Capacity Reasoning Models",
                "official_features": "5x capacity limits, voice throughput without throttling, Deep Research high compute",
                "source_status": "VERIFIED",
                "price_usd": 25.60,
                "price_idr": 410000,
                "store_price_usd": 25.60,
                "store_price_idr": 410000,
                "stock": 25,
                "sold": 390,
                "type": "Langganan Resmi 100% (Dedicated Pro 5X $100/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Batas kuota pesan 5x lebih tinggi dari Plus reguler (Pro 5X), akses model penalaran tingkat tinggi OpenAI, kuota agen Deep Research berkapasitas besar, Canvas, dan throughput voice tanpa throttling.",
                "how_to_use": "1. Data akun private diserahkan langsung oleh bot atau aktivasi pada email pribadi.\n2. Login melalui https://chatgpt.com.\n3. Nikmati kuota komputasi 5x lipat untuk alur kerja intensif.",
                "notes": "Langganan legal dan resmi 100%. OpenAI hanya menyediakan opsi billing bulanan untuk Pro $100. Dilindungi Full Garansi 1:1 Replacement."
            },
            {
                "id": "business_prem_1m",
                "short_name_id": "Business Prem (1 Bulan)",
                "short_name_en": "Business Prem (1 Month)",
                "name_en": "ChatGPT Business Premium — 1 Month (Billed Monthly)",
                "name_id": "ChatGPT Business Premium — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "ChatGPT Business Premium",
                "official_price_monthly": "$125/user/month (Monthly Billing)",
                "official_price_yearly": "$1,200/user/year ($100/user/mo billed annually)",
                "official_billing": "Monthly & Annual (Min 2 Seats)",
                "official_models": "Flagship 5X Capacity Reasoning & Enterprise Models",
                "official_features": "5x standard limits, no 5-hour limit, enterprise security, workspace credits option",
                "source_status": "VERIFIED",
                "price_usd": 32.00,
                "price_idr": 512000,
                "store_price_usd": 32.00,
                "store_price_idr": 512000,
                "stock": 15,
                "sold": 120,
                "type": "Langganan Resmi 100% (Business Premium $125/User/Bulan • 5X Capacity)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Tier tertinggi ruang kerja bisnis OpenAI ($125/user/bulan): Kuota 5X lebih besar dibanding Standard, prioritas komputasi enterprise, dan enkripsi data tingkat korporat.",
                "how_to_use": "1. Cantumkan email Anda saat pemesanan.\n2. Tautan invite Business Premium akan dikirimkan ke email Anda.\n3. Klik tautan untuk aktivasi workspace Premium.",
                "notes": "Langganan legal resmi enterprise. Dilindungi Full Garansi 1:1 Replacement selama 30 hari."
            },
            {
                "id": "pro_200_1m",
                "short_name_id": "Pro 20X $200 (1 Bulan)",
                "short_name_en": "Pro 20X $200 (1 Month)",
                "name_en": "ChatGPT Pro ($200 Plan / Pro 20X) — 1 Month (Active / Renewals)",
                "name_id": "ChatGPT Pro ($200 Plan / Pro 20X) — 1 Bulan (Akun Aktif)",
                "duration": "30 Hari",
                "official_plan": "ChatGPT Pro $200 Tier",
                "official_price_monthly": "$200/month (New signups paused per Sept 10, 2026; existing renewals active)",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "Unthrottled Reasoning & Highest Compute Models",
                "official_features": "Maximum compute access, unthrottled reasoning, Deep Research max pool",
                "source_status": "PARTIALLY VERIFIED (Active Account Only)",
                "price_usd": 51.20,
                "price_idr": 819000,
                "store_price_usd": 51.20,
                "store_price_idr": 819000,
                "stock": 8,
                "sold": 180,
                "type": "Langganan Resmi 100% (Dedicated Pro 20X $200/Bulan • Status: Active Account)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Tier Pro 20X tertinggi OpenAI ($200/bulan): Akses tak terbatas ke komputasi penalaran tertinggi OpenAI, kuota tanpa batas agen Deep Research, editor Canvas, dan prioritas server instan. Catatan: Pendaftaran baru di web resmi sedang dipause per September 2026, akun yang kami sediakan adalah akun resmi aktif dengan perpanjangan valid.",
                "how_to_use": "1. Kredensial akun resmi lengkap (Email + Password + 2FA) diserahkan instan.\n2. Login via https://chatgpt.com.\n3. Akses Pro 20X langsung aktif siap pakai.",
                "notes": "Akun resmi aktif dengan status renewal terverifikasi. Dilindungi Full Garansi 1:1 Replacement selama 30 hari penuh."
            },
            {
                "id": "business_std_1y",
                "short_name_id": "Business Std (1 Tahun)",
                "short_name_en": "Business Std (1 Year)",
                "name_en": "ChatGPT Business Standard — 1 Year (365 Days Official Annual Billing)",
                "name_id": "ChatGPT Business Standard — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "ChatGPT Business Standard Annual",
                "official_price_monthly": "$20/user/month equivalent",
                "official_price_yearly": "$240/user/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "ChatGPT Business Standard & Codex Models",
                "official_features": "12-month workspace access, Zero Data Retention, Custom GPTs sharing, admin console",
                "source_status": "VERIFIED",
                "price_usd": 61.44,
                "price_idr": 983000,
                "store_price_usd": 61.44,
                "store_price_idr": 983000,
                "stock": 20,
                "sold": 340,
                "type": "Langganan Resmi 100% (Business Standard Tahunan $240/User/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Akses 12 bulan penuh ke ruang kerja resmi ChatGPT Business Standard ($240/user/tahun tier). Batas kuota tinggi, zero data retention, Custom GPTs sharing, dan workspace management selama 1 tahun kalender.",
                "how_to_use": "1. Cantumkan email ChatGPT Anda saat checkout.\n2. Undangan resmi Business 1 Tahun akan dikirimkan langsung ke email Anda.\n3. Klik tautan undangan untuk mengaktifkan status Business selama 365 hari penuh.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            }
        ]
    },
    "claude": {
        "id": "claude",
        "name": "Claude",
        "icon": "🌸",
        "category": "Coding & High Intelligence",
        "badge": "OFFICIAL ANTHROPIC CLAUDE",
        "official_provider": "Anthropic",
        "description_en": "Official Anthropic Claude subscriptions: Pro (Monthly & Annual Official), Max 5x ($100 Tier - Monthly), and Max 20x ($200 Tier - Monthly) featuring Claude's latest frontier models, Claude Code CLI, and Projects (1M context).",
        "description_id": "Layanan resmi Anthropic: Claude Pro (Bulanan & Tahunan Resmi), Claude Max 5x ($100 Tier - Bulanan), dan Claude Max 20x ($200 Tier - Bulanan). Dilengkapi model frontier resmi Anthropic, CLI otonom Claude Code, Projects (1M konteks), dan Artifacts. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "pro_1m",
                "short_name_id": "Pro (1 Bulan)",
                "short_name_en": "Pro (1 Month)",
                "name_en": "Claude Pro — 1 Month Official (30 Days)",
                "name_id": "Claude Pro — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Claude Pro",
                "official_price_monthly": "$20/month",
                "official_price_yearly": "$200/year",
                "official_billing": "Monthly & Annual",
                "official_models": "Claude Frontier Models",
                "official_features": "5x usage vs Free, Projects (1M context), Claude Code CLI, Artifacts UI preview",
                "source_status": "VERIFIED",
                "price_usd": 5.12,
                "price_idr": 82000,
                "store_price_usd": 5.12,
                "store_price_idr": 82000,
                "stock": 70,
                "sold": 1950,
                "type": "Langganan Resmi 100% (Bulanan Resmi $20/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Langganan resmi bulanan Anthropic Claude Pro ($20/bulan tier): Kuota 5x lebih tinggi dibanding Free, fitur Projects 1M token konteks, Claude Code CLI, dan live Artifacts UI preview.",
                "how_to_use": "1. Akun (Email + Password) dikirimkan langsung oleh bot secara otomatis.\n2. Login di https://claude.ai atau aplikasi resmi Claude.\n3. Akses Pro aktif 30 hari penuh.",
                "notes": "Langganan legal dan resmi 100%. Jangan khawatir akun terbanned atau ter-suspend — dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "max_5x_1m",
                "short_name_id": "Max 5x $100 (1 Bulan)",
                "short_name_en": "Max 5x $100 (1 Month)",
                "name_en": "Claude Max 5x ($100 Plan) — 1 Month Official",
                "name_id": "Claude Max 5x ($100 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Claude Max 5x Tier",
                "official_price_monthly": "$100/month",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "Claude Frontier Models with 5x Limits",
                "official_features": "5x Pro usage limits, higher output limits, early access to advanced features",
                "source_status": "VERIFIED",
                "price_usd": 25.60,
                "price_idr": 410000,
                "store_price_usd": 25.60,
                "store_price_idr": 410000,
                "stock": 20,
                "sold": 290,
                "type": "Langganan Resmi 100% (Dedicated Max 5x $100/Bulan • Bulanan Saja)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Batas pesan 5x lebih tinggi dari Claude Pro standar, throughput pemrosesan cepat, alur kerja agen Claude Code, ruang kerja Projects 1M konteks, dan live Artifacts preview.",
                "how_to_use": "1. Data akun private dikirimkan langsung oleh bot atau aktivasi pada email pribadi.\n2. Login melalui https://claude.ai.\n3. Nikmati batas pesan 5x lipat untuk coding & riset intensif.",
                "notes": "Langganan legal dan resmi 100%. Anthropic hanya menyediakan opsi billing bulanan untuk tier Max. Dilindungi Full Garansi 1:1."
            },
            {
                "id": "pro_1y",
                "short_name_id": "Pro (1 Tahun)",
                "short_name_en": "Pro (1 Year)",
                "name_en": "Claude Pro — 1 Year Official (365 Days Annual Billing)",
                "name_id": "Claude Pro — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "Claude Pro Annual",
                "official_price_monthly": "$16.67/month equivalent",
                "official_price_yearly": "$200/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Claude Frontier Models",
                "official_features": "12-month access to Claude Pro ($200 upfront annual billing), Projects 1M context, Claude Code CLI",
                "source_status": "VERIFIED",
                "price_usd": 48.64,
                "price_idr": 778000,
                "store_price_usd": 48.64,
                "store_price_idr": 778000,
                "stock": 15,
                "sold": 490,
                "type": "Langganan Resmi 100% (Paket Tahunan Resmi Anthropic $200/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Akses resmi 12 bulan penuh ke paket tahunan Claude Pro ($200/tahun tier). Akses model frontier Claude, Claude Code CLI, Projects 1M context, interactive Artifacts visualizer, dan prioritas server stabil sepanjang 365 hari.",
                "how_to_use": "1. Pilih aktivasi pada email pribadi Anda atau gunakan akun private yang disediakan.\n2. Langganan aktif selama 1 tahun kalender penuh (365 hari) tanpa perlu perpanjang bulanan.\n3. Nikmati proteksi garansi penggantian selama masa aktif.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            },
            {
                "id": "max_20x_1m",
                "short_name_id": "Max 20x $200 (1 Bulan)",
                "short_name_en": "Max 20x $200 (1 Month)",
                "name_en": "Claude Max 20x ($200 Plan) — 1 Month Official",
                "name_id": "Claude Max 20x ($200 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Claude Max 20x Tier",
                "official_price_monthly": "$200/month",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "Claude Frontier Models with 20x Limits",
                "official_features": "20x Pro usage limits, priority during peak traffic, maximum compute",
                "source_status": "VERIFIED",
                "price_usd": 51.20,
                "price_idr": 819000,
                "store_price_usd": 51.20,
                "store_price_idr": 819000,
                "stock": 12,
                "sold": 160,
                "type": "Langganan Resmi 100% (Dedicated Max 20x $200/Bulan • Bulanan Saja)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Batas kuota penggunaan tertinggi 20x lipat dibanding Claude Pro reguler ($200/bulan tier), akses tak terbatas ke model frontier Claude, prioritas eksekusi untuk Claude Code CLI, dan Projects 1 Juta token konteks.",
                "how_to_use": "1. Kredensial akun resmi diserahkan lengkap (Email + Password + 2FA).\n2. Login melalui https://claude.ai atau aplikasi desktop/mobile resmi.\n3. Akses fitur Max aktif seketika.",
                "notes": "Langganan legal dan resmi 100%. Anthropic hanya menyediakan opsi billing bulanan untuk tier Max. Dilindungi Full Garansi 1:1."
            }
        ]
    },
    "perplexity": {
        "id": "perplexity",
        "name": "Perplexity",
        "icon": "🔍",
        "category": "Multi-Model Search & Research",
        "badge": "MULTI-FRONTIER AI ENGINE",
        "official_provider": "Perplexity AI",
        "description_en": "Official Perplexity AI subscriptions: Pro (Monthly & Annual Official) and Max ($200 Tier - Monthly & Annual via web app) offering multi-frontier model switching, Perplexity Computer autonomous browser agent, and Spaces.",
        "description_id": "Layanan resmi Perplexity AI: Perplexity Pro (Bulanan & Tahunan Resmi) dan Perplexity Max ($200 Tier - Bulanan & Tahunan Web). Platform pencarian multi-model frontier dengan akses bebas beralih model AI terkemuka, agen otonom Perplexity Computer, dan Spaces. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "pro_1m",
                "short_name_id": "Pro (1 Bulan)",
                "short_name_en": "Pro (1 Month)",
                "name_en": "Perplexity Pro — 1 Month Official (30 Days)",
                "name_id": "Perplexity Pro — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Perplexity Pro",
                "official_price_monthly": "$20/month",
                "official_price_yearly": "$200/year",
                "official_billing": "Monthly & Annual",
                "official_models": "Multi-Model Frontier Selection (OpenAI, Anthropic, Google, Sonar)",
                "official_features": "300+ Pro Searches per day, multi-model switcher, document analysis, Spaces",
                "source_status": "VERIFIED",
                "price_usd": 5.12,
                "price_idr": 82000,
                "store_price_usd": 5.12,
                "store_price_idr": 82000,
                "stock": 60,
                "sold": 1820,
                "type": "Langganan Resmi 100% (Bulanan Resmi $20/Bulan • Multi-Model)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi 30 hari ke Perplexity Pro bulanan ($20/bulan tier). 300+ Pro Searches per hari, upload file & dokumen tanpa batas, serta bebas memilih model frontier AI: OpenAI, Anthropic, Google, dan Sonar reasoning.",
                "how_to_use": "1. Akun diserahkan lengkap oleh bot atau diaktifkan langsung di akun Anda.\n2. Login di https://perplexity.ai.\n3. Pilih model AI favorit pada menu Settings > AI Model untuk memulai riset.",
                "notes": "Langganan legal dan resmi 100%. Jangan khawatir akun terbanned atau ter-suspend — dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "pro_1y",
                "short_name_id": "Pro (1 Tahun)",
                "short_name_en": "Pro (1 Year)",
                "name_en": "Perplexity Pro — 1 Year Official (365 Days Annual Billing)",
                "name_id": "Perplexity Pro — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "Perplexity Pro Annual",
                "official_price_monthly": "$16.67/month equivalent",
                "official_price_yearly": "$200/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Multi-Model Frontier Selection",
                "official_features": "12-month Perplexity Pro access, 300+ Pro Searches/day, file uploads, Spaces",
                "source_status": "VERIFIED",
                "price_usd": 48.64,
                "price_idr": 778000,
                "store_price_usd": 48.64,
                "store_price_idr": 778000,
                "stock": 25,
                "sold": 560,
                "type": "Langganan Resmi 100% (Paket Tahunan Resmi $200/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Akses resmi 12 bulan penuh ke paket tahunan Perplexity Pro ($200/tahun tier). Kuota 300+ Pro Searches harian, bebas beralih model frontier, upload dokumen tak terbatas, dan ruang kolaborasi Spaces sepanjang 365 hari.",
                "how_to_use": "1. Data login akun resmi dikirimkan langsung oleh bot.\n2. Login di https://perplexity.ai.\n3. Akun aktif selama 1 tahun kalender penuh (365 hari) dengan proteksi garansi total.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            },
            {
                "id": "max_200_1m",
                "short_name_id": "Max $200 (1 Bulan)",
                "short_name_en": "Max $200 (1 Month)",
                "name_en": "Perplexity Max ($200 Plan) — 1 Month Official",
                "name_id": "Perplexity Max ($200 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Perplexity Max",
                "official_price_monthly": "$200/month",
                "official_price_yearly": "$2,000/year (Web App)",
                "official_billing": "Monthly & Annual (Web App)",
                "official_models": "Multi-Model Frontier + Perplexity Computer Agent",
                "official_features": "Unrestricted Pro queries, access to Perplexity Computer autonomous browser agent",
                "source_status": "VERIFIED",
                "price_usd": 51.20,
                "price_idr": 819000,
                "store_price_usd": 51.20,
                "store_price_idr": 819000,
                "stock": 8,
                "sold": 110,
                "type": "Langganan Resmi 100% (Perplexity Max $200/Bulan • Bulanan Saja)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Tier tertinggi individu Perplexity AI ($200/bulan): Akses tak terbatas ke agen peramban otonom 'Perplexity Computer', query Pro tanpa batas kuota harian, Model Council multi-LLM debate, dan prioritas komputasi tertinggi.",
                "how_to_use": "1. Kredensial akun resmi dikirimkan otomatis.\n2. Login ke https://www.perplexity.ai.\n3. Aktifkan mode 'Perplexity Computer' untuk riset otonom tingkat lanjut.",
                "notes": "Langganan legal dan resmi 100%. Tersedia opsi billing bulanan & tahunan resmi di web app. Dilindungi Full Garansi 1:1 Replacement."
            }
        ]
    },
    "grok": {
        "id": "grok",
        "name": "Grok",
        "icon": "⚡",
        "category": "Realtime AI & Reasoning",
        "badge": "OFFICIAL xAI GROK",
        "official_provider": "xAI",
        "description_en": "Official xAI Grok subscriptions: SuperGrok Lite ($10 Tier - Monthly), SuperGrok ($30 Tier - Monthly), and SuperGrok Plus ($100 Tier - Monthly) featuring Grok 4.6, Think Mode, Grok DeepSearch, and image/video generation.",
        "description_id": "Layanan resmi xAI Grok: SuperGrok Lite ($10 Tier - Bulanan), SuperGrok ($30 Tier - Bulanan), dan SuperGrok Plus ($100 Tier - Bulanan). Ditenagai model penalaran resmi Grok 4.6 (sesuai paket xAI), Think Mode, Grok DeepSearch, serta pembuatan gambar & video. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "supergrok_lite_1m",
                "short_name_id": "Lite $10 (1 Bulan)",
                "short_name_en": "Lite $10 (1 Month)",
                "name_en": "SuperGrok Lite ($10 Plan) — 1 Month Official",
                "name_id": "SuperGrok Lite ($10 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "SuperGrok Lite",
                "official_price_monthly": "$10/month",
                "official_price_yearly": "N/A (Monthly Only on grok.com)",
                "official_billing": "Monthly Only",
                "official_models": "Grok Standard Model",
                "official_features": "Standard message limits, realtime web search, Grok Imagine",
                "source_status": "VERIFIED",
                "price_usd": 2.56,
                "price_idr": 41000,
                "store_price_usd": 2.56,
                "store_price_idr": 41000,
                "stock": 25,
                "sold": 380,
                "type": "Langganan Resmi 100% (SuperGrok Lite $10/Bulan • grok.com)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi portal grok.com tier Lite ($10/bulan): Akses ke Grok dengan kuota standar, pencarian web real-time, dan Grok Imagine image generator.",
                "how_to_use": "1. Akun siap pakai dikirimkan otomatis oleh bot.\n2. Login di https://grok.com atau aplikasi resmi Grok.\n3. Mulai eksplorasi fitur Grok dengan kuota resmi.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "supergrok_1m",
                "short_name_id": "SuperGrok $30 (1 Bulan)",
                "short_name_en": "SuperGrok $30 (1 Month)",
                "name_en": "SuperGrok Standalone ($30 Plan) — 1 Month Official",
                "name_id": "SuperGrok Standalone ($30 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "SuperGrok",
                "official_price_monthly": "$30/month",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "Grok 4.6 (Official Plan Listing)",
                "official_features": "Grok Bot, Think Mode, image & video generation, expert features, higher rate limits",
                "source_status": "VERIFIED",
                "price_usd": 7.68,
                "price_idr": 123000,
                "store_price_usd": 7.68,
                "store_price_idr": 123000,
                "stock": 30,
                "sold": 420,
                "type": "Langganan Resmi 100% (SuperGrok $30/Bulan • grok.com)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi portal grok.com tier $30/bulan: Batas kuota pesan tinggi untuk model Grok 4.6 (sesuai halaman paket resmi xAI), mode penalaran Think Mode, pencarian mendalam Grok DeepSearch, generator gambar & video, dan akses Expert Mode.",
                "how_to_use": "1. Akun siap pakai dikirimkan otomatis setelah checkout.\n2. Login di https://grok.com atau aplikasi Grok.\n3. Akses fitur SuperGrok aktif selama 30 hari penuh.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "supergrok_plus_1m",
                "short_name_id": "Plus $100 (1 Bulan)",
                "short_name_en": "Plus $100 (1 Month)",
                "name_en": "SuperGrok Plus ($100 Plan) — 1 Month Official",
                "name_id": "SuperGrok Plus ($100 Plan) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "SuperGrok Plus",
                "official_price_monthly": "$100/month",
                "official_price_yearly": "N/A (Monthly Only)",
                "official_billing": "Monthly Only",
                "official_models": "Grok High Priority Compute",
                "official_features": "Significantly higher limits across chat, voice, build, 1080p video creation, priority compute",
                "source_status": "VERIFIED",
                "price_usd": 25.60,
                "price_idr": 410000,
                "store_price_usd": 25.60,
                "store_price_idr": 410000,
                "stock": 15,
                "sold": 180,
                "type": "Langganan Resmi 100% (SuperGrok Plus $100/Bulan • Bulanan Saja)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses prioritas tinggi ke model penalaran Grok, kuota mingguan berkapasitas sangat besar, pemrosesan video 1080p dengan AI, Grok DeepSearch untuk analisis data real-time, dan generator visual.",
                "how_to_use": "1. Data akun dikirimkan oleh bot setelah pembayaran terverifikasi.\n2. Login di https://grok.com.\n3. Mulai riset dan pembuatan konten dengan kapasitas komputasi tinggi.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            }
        ]
    },
    "cursor": {
        "id": "cursor",
        "name": "Cursor",
        "icon": "💻",
        "category": "AI Coding Platform & Agents",
        "badge": "OFFICIAL CURSOR AI",
        "official_provider": "Cursor (Anysphere)",
        "description_en": "Official Cursor AI subscriptions: Cursor Hobby (Free), Cursor Pro ($20/Month & $192/Year Official - Save 20%), Cursor Teams Standard ($40/Seat/Month), Cursor Pro+ ($60/Month - 3x Limits), and Cursor Ultra ($200/Month - 20x Limits) featuring Composer multi-file agent and unlimited Cursor Tab completions.",
        "description_id": "Layanan resmi Cursor AI: Cursor Hobby (Gratis), Cursor Pro ($20/Bulan & $192/Tahun Resmi - Hemat 20%), Cursor Teams Standard ($40/Seat/Bulan), Cursor Pro+ ($60/Bulan - Kuota 3x), dan Cursor Ultra ($200/Bulan - Kuota 20x). Platform coding AI dengan agen otonom Composer multi-file dan autocompletion tanpa batas Cursor Tab. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "cursor_pro_1m",
                "short_name_id": "Pro (1 Bulan)",
                "short_name_en": "Pro (1 Month)",
                "name_en": "Cursor Pro — 1 Month Official (30 Days)",
                "name_id": "Cursor Pro — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Cursor Pro",
                "official_price_monthly": "$20/month",
                "official_price_yearly": "$192/year ($16/month equivalent, save 20%)",
                "official_billing": "Monthly & Annual",
                "official_models": "Multi-Model Access in Cursor",
                "official_features": "Monthly Fast Requests pool, unlimited Cursor Tab predictions, Composer multi-file agent",
                "source_status": "VERIFIED",
                "price_usd": 5.12,
                "price_idr": 82000,
                "store_price_usd": 5.12,
                "store_price_idr": 82000,
                "stock": 65,
                "sold": 1980,
                "type": "Langganan Resmi 100% (Bulanan Resmi $20/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Paket resmi bulanan Cursor Pro ($20/bulan tier): Kuota Fast Requests bulanan untuk model frontier, agen otonom Composer, dan autocompletion prediktif tanpa batas Cursor Tab.",
                "how_to_use": "1. Akun siap pakai diberikan otomatis oleh bot.\n2. Login di Cursor IDE melalui menu Settings > Accounts.\n3. Mulai kembangkan kode dengan efisiensi AI 10x lebih cepat.",
                "notes": "Langganan legal dan resmi 100%. Jangan khawatir akun terbanned atau ter-suspend — dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "cursor_teams_1m",
                "short_name_id": "Teams Std (1 Bulan)",
                "short_name_en": "Teams Std (1 Month)",
                "name_en": "Cursor Teams Standard — 1 Month (Official $40/Seat)",
                "name_id": "Cursor Teams Standard — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Cursor Teams Standard",
                "official_price_monthly": "$40/user/month",
                "official_price_yearly": "Available in admin console",
                "official_billing": "Monthly (+ Annual)",
                "official_models": "Multi-Model with Privacy Mode",
                "official_features": "100% Privacy Mode, admin dashboard, team context sharing, centralized billing",
                "source_status": "VERIFIED",
                "price_usd": 10.24,
                "price_idr": 164000,
                "store_price_usd": 10.24,
                "store_price_idr": 164000,
                "stock": 25,
                "sold": 340,
                "type": "Langganan Resmi 100% (Cursor Business $40/Seat/Bulan • Privacy Mode)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Ruang kerja resmi Cursor Teams ($40/seat/bulan). Enforce Privacy Mode 100% di mana kode sumber tidak disimpan di server pihak ketiga, konsol administrasi terpusat, dan integrasi SSO.",
                "how_to_use": "1. Cantumkan email Anda saat pembelian.\n2. Tautan undangan resmi Cursor Teams akan dikirimkan ke email Anda.\n3. Klik tautan untuk mengaktifkan akun di workspace bisnis.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "cursor_pro_plus_1m",
                "short_name_id": "Pro+ 3x $60 (1 Bulan)",
                "short_name_en": "Pro+ 3x $60 (1 Month)",
                "name_en": "Cursor Pro+ ($60 Plan / 3x Limits) — 1 Month Official",
                "name_id": "Cursor Pro+ ($60 Plan / 3x Limits) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Cursor Pro+",
                "official_price_monthly": "$60/month",
                "official_price_yearly": "$576/year ($48/month, save 20%)",
                "official_billing": "Monthly & Annual",
                "official_models": "Multi-Model with 3x Capacity",
                "official_features": "3x Fast Request Limits / Agent capacity pool, Composer multi-file agent",
                "source_status": "VERIFIED",
                "price_usd": 15.36,
                "price_idr": 246000,
                "store_price_usd": 15.36,
                "store_price_idr": 246000,
                "stock": 25,
                "sold": 310,
                "type": "Langganan Resmi 100% (Cursor Pro+ $60/Bulan • 3x Agent Pool)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Kapasitas kredit 3x lebih besar dibanding paket Pro biasa ($60/bulan tier), alokasi Fast Requests melimpah untuk model frontier, eksekusi multi-file Composer, dan autocompletion tanpa batas Cursor Tab.",
                "how_to_use": "1. Akun dikirimkan otomatis oleh bot setelah verifikasi order.\n2. Login ke Cursor IDE.\n3. Bekerja tanpa khawatir batas limit harian habis di tengah proyek.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "cursor_pro_1y",
                "short_name_id": "Pro (1 Tahun / -20%)",
                "short_name_en": "Pro (1 Year / -20%)",
                "name_en": "Cursor Pro — 1 Year Official (365 Days Annual Billing - Save 20%)",
                "name_id": "Cursor Pro — 1 Tahun (365 Hari Resmi - Hemat 20%)",
                "duration": "365 Hari",
                "official_plan": "Cursor Pro Annual",
                "official_price_monthly": "$16/month equivalent",
                "official_price_yearly": "$192/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Multi-Model Access in Cursor",
                "official_features": "12-month access to Cursor Pro ($192/year billed yearly), Fast Requests pool, unlimited Cursor Tab",
                "source_status": "VERIFIED",
                "price_usd": 47.10,
                "price_idr": 754000,
                "store_price_usd": 47.10,
                "store_price_idr": 754000,
                "stock": 20,
                "sold": 520,
                "type": "Langganan Resmi 100% (Paket Tahunan Resmi $192/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Akses resmi 12 bulan penuh ke paket tahunan Cursor Pro ($192/tahun billed yearly, $16/bulan tier). Kuota Fast Requests diperbarui setiap bulan secara otomatis, unlimited Cursor Tab, Composer Agent, dan prioritas server stabil sepanjang 365 hari.",
                "how_to_use": "1. Akun private 1 tahun diserahkan lengkap setelah checkout.\n2. Login di Cursor IDE.\n3. Akses Pro aktif 365 hari penuh tanpa perlu bayar tagihan bulanan.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            },
            {
                "id": "cursor_ultra_1m",
                "short_name_id": "Ultra 20x $200 (1 Bulan)",
                "short_name_en": "Ultra 20x $200 (1 Month)",
                "name_en": "Cursor Ultra ($200 Plan / 20x Limits) — 1 Month Official",
                "name_id": "Cursor Ultra ($200 Plan / 20x Limits) — 1 Bulan",
                "duration": "30 Hari",
                "official_plan": "Cursor Ultra",
                "official_price_monthly": "$200/month",
                "official_price_yearly": "N/A",
                "official_billing": "Monthly Only",
                "official_models": "Multi-Model with 20x Massive Agent Pool",
                "official_features": "20x Limits for intensive all-day multi-file agent execution, fastest compute queue",
                "source_status": "VERIFIED",
                "price_usd": 51.20,
                "price_idr": 819000,
                "store_price_usd": 51.20,
                "store_price_idr": 819000,
                "stock": 10,
                "sold": 130,
                "type": "Langganan Resmi 100% (Cursor Ultra $200/Bulan • 20x Agent Pool)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Tier tertinggi Cursor AI ($200/bulan): Kolam kredit 20x lipat lebih besar dibanding Pro standar, akses tanpa hambatan ke model frontier, eksekusi loop agen otonom Composer untuk refactoring codebase besar, dan prioritas antrean tercepat.",
                "how_to_use": "1. Akun resmi diserahkan lengkap (Email + Password + Token Login).\n2. Login di aplikasi desktop Cursor (https://cursor.com).\n3. Buka panel Composer dan nikmati kuota ultra untuk pembangunan proyek kompleks.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga detik terakhir durasi 30 hari selesai."
            }
        ]
    },
    "leonardo": {
        "id": "leonardo",
        "name": "Leonardo",
        "icon": "🎨",
        "category": "Generative Art & Visual AI",
        "badge": "OFFICIAL LEONARDO AI",
        "official_provider": "Leonardo.ai (Canva)",
        "description_en": "Official Leonardo.ai subscriptions: Free ($0), Essential ($12/Month & $120/Year), Premium ($30/Month & $288/Year), and Ultimate ($60/Month & $576/Year - Save ~20% Yearly) featuring Lucid Origin, Phoenix 1.0, Motion 2.0 Video AI, and private token banks.",
        "description_id": "Layanan resmi Leonardo.ai: Free ($0), Essential ($12/Bulan & $120/Tahun), Premium ($30/Bulan & $288/Tahun), dan Ultimate ($60/Bulan & $576/Tahun Resmi - Hemat ~20% Tahunan). Platform visual AI dengan model Lucid Origin, Phoenix 1.0, Motion 2.0 Video AI, dan token bank privat. 100% Langganan Resmi Legal, Aman Anti-Banned, dan Full Garansi 1:1 hingga durasi berakhir.",
        "plans": [
            {
                "id": "essential_1m",
                "short_name_id": "Essential (1 Bulan)",
                "short_name_en": "Essential (1 Month)",
                "name_en": "Leonardo Essential — 1 Month Official (30 Days)",
                "name_id": "Leonardo Essential — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Leonardo Essential",
                "official_price_monthly": "$12/month",
                "official_price_yearly": "$120/year ($10/month equivalent, save 20%)",
                "official_billing": "Monthly & Annual",
                "official_models": "Lucid Origin, Phoenix 1.0, and Core Platform Models",
                "official_features": "8,500 fast tokens/month, 2 concurrent jobs, private image feed, commercial rights",
                "source_status": "VERIFIED",
                "price_usd": 3.07,
                "price_idr": 49000,
                "store_price_usd": 3.07,
                "store_price_idr": 49000,
                "stock": 50,
                "sold": 920,
                "type": "Langganan Resmi 100% (Essential Bulanan $12/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi paket Essential ($12/bulan tier): 8.500 Fast Tokens bulanan, 2 concurrent jobs, akses model Lucid Origin, Phoenix 1.0, private image feed tanpa watermark, dan lisensi komersial penuh.",
                "how_to_use": "1. Akun (Email + Password) diserahkan langsung setelah checkout.\n2. Login di https://leonardo.ai.\n3. Mulai hasilkan gambar AI berkualitas tinggi.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "premium_1m",
                "short_name_id": "Premium (1 Bulan)",
                "short_name_en": "Premium (1 Month)",
                "name_en": "Leonardo Premium — 1 Month Official (30 Days)",
                "name_id": "Leonardo Premium — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Leonardo Premium",
                "official_price_monthly": "$30/month",
                "official_price_yearly": "$288/year ($24/month equivalent, save 20%)",
                "official_billing": "Monthly & Annual",
                "official_models": "Lucid Origin, Phoenix 1.0, Motion 2.0",
                "official_features": "25,000 fast tokens/month, unlimited relaxed generation, Motion 2.0, Canvas Editor",
                "source_status": "VERIFIED",
                "price_usd": 7.68,
                "price_idr": 123000,
                "store_price_usd": 7.68,
                "store_price_idr": 123000,
                "stock": 35,
                "sold": 680,
                "type": "Langganan Resmi 100% (Premium Bulanan $30/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Akses resmi paket Premium ($30/bulan tier): 25.000 Fast Tokens per bulan, Relaxed generations tanpa batas kuota, 3 concurrent jobs, akses model Lucid Origin, Phoenix 1.0, private feed, dan Canvas Editor.",
                "how_to_use": "1. Akun siap pakai dikirimkan otomatis oleh bot.\n2. Login ke https://leonardo.ai.\n3. Mulai buat aset seni visual dan ilustrasi kelas profesional.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "ultimate_1m",
                "short_name_id": "Ultimate (1 Bulan)",
                "short_name_en": "Ultimate (1 Month)",
                "name_en": "Leonardo Ultimate — 1 Month Official (30 Days)",
                "name_id": "Leonardo Ultimate — 1 Bulan (30 Hari)",
                "duration": "30 Hari",
                "official_plan": "Leonardo Ultimate",
                "official_price_monthly": "$60/month",
                "official_price_yearly": "$576/year ($48/month equivalent, save 20%)",
                "official_billing": "Monthly & Annual",
                "official_models": "Lucid Origin, Phoenix 1.0, Motion 2.0 Video AI",
                "official_features": "60,000 fast tokens/month, unlimited relaxed generation, Motion 2.0 Video AI",
                "source_status": "VERIFIED",
                "price_usd": 15.36,
                "price_idr": 246000,
                "store_price_usd": 15.36,
                "store_price_idr": 246000,
                "stock": 15,
                "sold": 210,
                "type": "Langganan Resmi 100% (Ultimate Bulanan $60/Bulan • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 30 Hari Selesai",
                "features": "Tier tertinggi individu Leonardo.ai ($60/bulan tier): 60.000 Fast Tokens per bulan, pembuatan gambar Relaxed tanpa batas kuota, 6 concurrent jobs, akses model Lucid Origin, Phoenix 1.0, Motion 2.0, dan generator video AI.",
                "how_to_use": "1. Akun resmi diserahkan langsung oleh bot.\n2. Login ke https://leonardo.ai.\n3. Nikmati kuota token berkapasitas besar untuk kreasi seni visual kelas atas.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-30 selesai."
            },
            {
                "id": "essential_1y",
                "short_name_id": "Essential (1 Tahun)",
                "short_name_en": "Essential (1 Year)",
                "name_en": "Leonardo Essential — 1 Year Official (365 Days Annual Billing)",
                "name_id": "Leonardo Essential — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "Leonardo Essential Annual",
                "official_price_monthly": "$10/month equivalent",
                "official_price_yearly": "$120/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Lucid Origin, Phoenix 1.0, and Core Platform Models",
                "official_features": "102,000 Fast Tokens yearly (8,500/mo), 2 concurrent jobs, commercial rights",
                "source_status": "VERIFIED",
                "price_usd": 30.72,
                "price_idr": 492000,
                "store_price_usd": 30.72,
                "store_price_idr": 492000,
                "stock": 20,
                "sold": 410,
                "type": "Langganan Resmi 100% (Essential Tahunan $120/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Akses 1 tahun penuh ke paket Essential ($120/tahun tier, $10/bulan): Total 102.000 Fast Tokens (8.500 Fast Tokens/bulan), 2 concurrent jobs, model Lucid Origin, Phoenix 1.0, private generation, dan hak komersial.",
                "how_to_use": "1. Data login akun diserahkan langsung oleh bot.\n2. Login di https://leonardo.ai.\n3. Nikmati kuota token resmi selama 1 tahun penuh.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            },
            {
                "id": "premium_1y",
                "short_name_id": "Premium (1 Tahun)",
                "short_name_en": "Premium (1 Year)",
                "name_en": "Leonardo Premium — 1 Year Official (365 Days Annual Billing)",
                "name_id": "Leonardo Premium — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "Leonardo Premium Annual",
                "official_price_monthly": "$24/month equivalent",
                "official_price_yearly": "$288/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Lucid Origin, Phoenix 1.0, Motion 2.0",
                "official_features": "300,000 Fast Tokens yearly (25,000/mo), unlimited relaxed generation, Canvas Editor",
                "source_status": "VERIFIED",
                "price_usd": 71.68,
                "price_idr": 1147000,
                "store_price_usd": 71.68,
                "store_price_idr": 1147000,
                "stock": 15,
                "sold": 240,
                "type": "Langganan Resmi 100% (Premium Tahunan $288/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Paket tahunan resmi Leonardo Premium ($288/tahun tier, $24/bulan): Total 300.000 Fast Tokens (25.000 Fast Tokens/bulan), unlimited relaxed generation, 3 concurrent generation jobs, model Lucid Origin & Phoenix 1.0, private feed, dan lisensi komersial.",
                "how_to_use": "1. Akun diserahkan lengkap oleh bot.\n2. Login di https://leonardo.ai.\n3. Langganan aktif selama 365 hari kalender.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            },
            {
                "id": "ultimate_1y",
                "short_name_id": "Ultimate (1 Tahun)",
                "short_name_en": "Ultimate (1 Year)",
                "name_en": "Leonardo Ultimate — 1 Year Official (365 Days Annual Billing)",
                "name_id": "Leonardo Ultimate — 1 Tahun (365 Hari Resmi)",
                "duration": "365 Hari",
                "official_plan": "Leonardo Ultimate Annual",
                "official_price_monthly": "$48/month equivalent",
                "official_price_yearly": "$576/year",
                "official_billing": "Annual Billing (365 Days)",
                "official_models": "Lucid Origin, Phoenix 1.0, Motion 2.0 Video AI",
                "official_features": "720,000 Fast Tokens yearly (60,000/mo), unlimited relaxed generation, Motion 2.0 Video AI",
                "source_status": "VERIFIED",
                "price_usd": 143.36,
                "price_idr": 2294000,
                "store_price_usd": 143.36,
                "store_price_idr": 2294000,
                "stock": 8,
                "sold": 85,
                "type": "Langganan Resmi 100% (Ultimate Tahunan $576/Tahun • Anti-Banned)",
                "warranty": "Full Garansi Penuh 1:1 Hingga 365 Hari Selesai",
                "features": "Paket tahunan resmi Leonardo Ultimate ($576/tahun tier, $48/bulan): Total 720.000 Fast Tokens (60.000 Fast Tokens/bulan), unlimited relaxed generation, 6 concurrent jobs, private image feed, dan Motion 2.0 Video AI.",
                "how_to_use": "1. Kredensial akun private diserahkan lengkap.\n2. Login di https://leonardo.ai.\n3. Akun aktif selama 1 tahun kalender penuh dengan garansi penuh.",
                "notes": "Langganan legal dan resmi 100%. Dilindungi Full Garansi 1:1 Replacement hingga hari ke-365 selesai."
            }
        ]
    }
}

PRODUCTS_LIST = ["chatgpt", "claude", "perplexity", "grok", "cursor", "leonardo"]

def get_product(product_id: str) -> dict | None:
    return PRODUCTS.get(product_id)

def get_product_plan(product_id: str, plan_id: str) -> dict | None:
    prod = PRODUCTS.get(product_id)
    if not prod:
        return None
    for p in prod.get("plans", []):
        if p["id"] == plan_id:
            return p
    return None
